name: to_do_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_slidable: ^3.0.1
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  hydrated_bloc: ^9.1.4
  equatable: ^2.0.5
  path_provider: ^2.1.2
  meta: ^1.11.0

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true